import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  Car,
  BarChart3,
  Home,
  Mail,
  Send,
  Calendar,
  Wallet,
} from "lucide-react";
import "./globals.css";
import Link from "next/link";
import StoreProvider from "./StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = [
  {
    href: "/",
    label: "Головна",
    icon: Home,
  },
  {
    href: "/PriceAnalysis",
    label: "Аналіз цін",
    icon: BarChart3,
  },
  {
    href: "/PriceYears",
    label: "Ціни по роках",
    icon: Calendar,
  },
  {
    href: "/PriceBudget",
    label: "Підбір за бюджетом",
    icon: Wallet,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 flex flex-col">
          {/* Header */}
          <header className="bg-white/80 backdrop-blur-lg border-b border-blue-100/50 sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                <Link href="/" className="flex items-center space-x-3 group">
                  <div className="w-10 h-10 bg-gradient-to-r from-blue-600 to-indigo-600 rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform duration-200">
                    <Car className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h1 className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                      AutoPricer
                    </h1>
                    <p className="text-xs text-slate-500 -mt-1">
                      Аналіз автомобільних цін
                    </p>
                  </div>
                </Link>

                <nav className="hidden md:flex items-center space-x-1 lg:space-x-2">
                  {navLinks.map((link) => (
                    <Link
                      key={link.href}
                      href={link.href}
                      className={`flex items-center space-x-2 px-2 py-2 lg:px-3 rounded-xl transition-all duration-200 text-sm font-medium`}
                    >
                      <link.icon className="w-4 h-4" />
                      <span>{link.label}</span>
                    </Link>
                  ))}
                </nav>
              </div>
            </div>
          </header>

          {/* Main Content */}
          <StoreProvider>
            <main className="flex-1">{children}</main>
          </StoreProvider>

          {/* Footer */}
          <footer className="bg-white/70 backdrop-blur-sm border-t border-slate-200/50 mt-16">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
              <div className="flex flex-col md:flex-row justify-between items-center gap-6 text-center md:text-left">
                <p className="text-slate-500 text-sm">
                  © 2025 AutoPricer. Всі права захищені.
                </p>
                <div className="flex items-center justify-center gap-4 md:gap-6 flex-wrap">
                  <a
                    href="mailto:traktoryiavtoad@gmail.com"
                    className="flex items-center gap-2 text-slate-600 hover:text-blue-600 transition-colors text-sm"
                  >
                    <Mail className="w-4 h-4" />
                    <span>traktoryiavtoad@gmail.com</span>
                  </a>
                  <a
                    href="https://t.me/traktoryiavto"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 text-slate-600 hover:text-blue-600 transition-colors text-sm"
                  >
                    <Send className="w-4 h-4" />
                    <span>Телеграм</span>
                  </a>
                </div>
                <Link
                  href="PrivacyPolicy"
                  className="text-slate-500 hover:text-blue-600 text-sm transition-colors"
                >
                  Політика конфіденційності
                </Link>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
